### ISSUE TITLE
Não é possível criar pedido

### ISSUE THREAD

**Issue by Leeh91** [mundipagg/MundiApi-NodeJS#17]
Bom dia,

estou tentando utilizar o sdk de vocês, mas não consigo criar um pedido. Sempre lança o mesmo erro:

Objeto do payload

{ code: 5aedc93a5249620a1002b408,
  customer_id: 'cus_67vnkPOCdiWZNPW5',
  items: [ { amount: 10, description: 'Produto Teste', quantity: 2 } ],
  card_id: 'card_BOra7o3ukqfQ7Zkj',
  shipping: 
   { amount: 60,
     address: { _id: 5aecfea270524f47f4c6565c,
        label: 'Casa',
        isDeliveryAddress: true,
        zip_code: '17658-511',
        neighborhood: 'Loteamento Vale das Flores',
        city: 'Joanopolis',
        street: 'Estrada Fazenda Nova União',
        number: '85',
        addAddress: 'casa 64',
        country: 'Brasil' } } }

Exception gerada

RangeError: Maximum call stack size exceeded
    at Function.cleanObject (/home/leandro/LambdaCode/Peranovich/node_modules/mundipagg-nodejs/lib/APIHelper.js:122:23)
    at Function.cleanObject (/home/leandro/LambdaCode/Peranovich/node_modules/mundipagg-nodejs/lib/APIHelper.js:140:22)
    at Function.cleanObject (/home/leandro/LambdaCode/Peranovich/node_modules/mundipagg-nodejs/lib/APIHelper.js:138:22)
    at Function.cleanObject (/home/leandro/LambdaCode/Peranovich/node_modules/mundipagg-nodejs/lib/APIHelper.js:140:22)
    at Function.cleanObject (/home/leandro/LambdaCode/Peranovich/node_modules/mundipagg-nodejs/lib/APIHelper.js:138:22)
    at Function.cleanObject (/home/leandro/LambdaCode/Peranovich/node_modules/mundipagg-nodejs/lib/APIHelper.js:140:22)
    at Function.cleanObject (/home/leandro/LambdaCode/Peranovich/node_modules/mundipagg-nodejs/lib/APIHelper.js:138:22)
    at Function.cleanObject (/home/leandro/LambdaCode/Peranovich/node_modules/mundipagg-nodejs/lib/APIHelper.js:140:22)
    at Function.cleanObject (/home/leandro/LambdaCode/Peranovich/node_modules/mundipagg-nodejs/lib/APIHelper.js:138:22)
    at Function.cleanObject (/home/leandro/LambdaCode/Peranovich/node_modules/mundipagg-nodejs/lib/APIHelper.js:140:22)
    at Function.cleanObject (/home/leandro/LambdaCode/Peranovich/node_modules/mundipagg-nodejs/lib/APIHelper.js:138:22)
    at Function.cleanObject (/home/leandro/LambdaCode/Peranovich/node_modules/mundipagg-nodejs/lib/APIHelper.js:140:22)
    at Function.cleanObject (/home/leandro/LambdaCode/Peranovich/node_modules/mundipagg-nodejs/lib/APIHelper.js:138:22)
    at Function.cleanObject (/home/leandro/LambdaCode/Peranovich/node_modules/mundipagg-nodejs/lib/APIHelper.js:140:22)
    at Function.cleanObject (/home/leandro/LambdaCode/Peranovich/node_modules/mundipagg-nodejs/lib/APIHelper.js:138:22)
    at Function.cleanObject (/home/leandro/LambdaCode/Peranovich/node_modules/mundipagg-nodejs/lib/APIHelper.js:140:22)
    at Function.cleanObject (/home/leandro/LambdaCode/Peranovich/node_modules/mundipagg-nodejs/lib/APIHelper.js:138:22)
    at Function.cleanObject (/home/leandro/LambdaCode/Peranovich/node_modules/mundipagg-nodejs/lib/APIHelper.js:140:22)
    at Function.cleanObject (/home/leandro/LambdaCode/Peranovich/node_modules/mundipagg-nodejs/lib/APIHelper.js:138:22)
    at Function.cleanObject (/home/leandro/LambdaCode/Peranovich/node_modules/mundipagg-nodejs/lib/APIHelper.js:140:22)
    at Function.cleanObject (/home/leandro/LambdaCode/Peranovich/node_modules/mundipagg-nodejs/lib/APIHelper.js:138:22)
    at Function.cleanObject (/home/leandro/LambdaCode/Peranovich/node_modules/mundipagg-nodejs/lib/APIHelper.js:140:22)

**Comment by Leeh91** [comment]
Bom dia, 

apenas para contribuir com outros utilizadores.

Solucionei o problema! 

Tinha um objeto com propriedades hidden de Embedded documents que gerava o erro relatado anteriormente.

A solução foi dar um JSON.stringify e depois um JSON.parse no objeto, assim eu consegui passar para a API um objeto json sem estas propriedades.
